name: rsue_schedule_backup_service
description: A sample command-line application for backup RSUE schedule.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0-266.7.beta <3.0.0'

dependencies:
  path: ^1.8.0
  rsue_schedule_api:
    git:
      url: https://github.com/pwrshi/rsue-schedule-api.git
      ref: v2

dev_dependencies:
  lints: ^2.0.0
